steps:
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'client'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    dir: 'client'
    args: ['run', 'build']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'frontend-service'
      - '--source=client'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'

timeout: '900s'
