steps:
  # === Backend ===
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'server'
    args: ['install']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'backend-service'
      - '--source=server'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'

  # === Frontend ===
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'client'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    dir: 'client'
    args: ['run', 'build']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'frontend-service'
      - '--source=client'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'

timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY
