steps:
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'server'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    dir: 'server'
    args: ['run', 'build']  # Optional: only if you use build step

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'backend-service'
      - '--source=server'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'

timeout: '900s'
